language: python
python:
  - "3.6"
before_install:
  - python --version
install:
  - pip install -r requirements-test.txt
  - python -m spacy download en
# command to run tests
script:
  - pytest --cov=chariot tests/
after_success:
  codecov
