site_name: chariot
site_description: Deliver the ready-to-train data to your NLP model.
repo_url: https://github.com/chakki-works/chariot
edit_uri: ""
site_author: chakki-works
nav:
    - Home: index.md
    - Tutorial:
        - Installation: tutorial/install.md
        - Make preprocessors: tutorial/make_preprocessor.md
        - Make a preprocessor pipeline: tutorial/make_pipeline.md
        - Work with your Model: tutorial/model_integration.md
        - Prepare NLP resources: tutorial/prepare_resources.md
        - Make custom preprocessors: tutorial/make_custom_preprocessor.md
    - Demo: https://github.com/chakki-works/chariot/blob/master/notebooks/movie_review_sentiment_analysis.ipynb
    - Documentation: document.md
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: docs/custom_theme
