site_name: chariot
site_description: Deliver the ready-to-train data to your NLP model.
repo_url: https://github.com/chakki-works/chariot
edit_uri: ""
site_author: chakki-works
pages:
    - Home: index.md
    - Features: features.md
    - User Guide:
        - Installation: install.md
        - Basic Usage: usage.md
